## Project Description
The project required downloading zip files from a study called the Human Activity Recognition Using Smartphones dataset and merging 
the traning and test datasets into one file along with subject and activity variables and adding column headings.  
The datset was then subset to only columns recording the mean or standard deviation of particular variables.
The final output is a smaller, tidy dataset that has the average of each variable by subject and activity

##Study design and data processing

###Collection of the raw data
The Human Activity Recognition Using Smartphones experiments comprised a group of 30 volunteers aged 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, the 3-axial linear acceleration and 3-axial angular velocity was captured at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

For each record in the dataset, data is provided for:
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope.
- A 561-feature vector with time and frequency domain variables.
- Its activity label.
- An identifier of the subject who carried out the experiment. 

##Creating the tidy datafile

###Guide to create the tidy data file
1. The raw data files were downloaded from [https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip]()
2. The training and the test sets were merged to create one dataset
    -Column names were added to the individual training (X_train.txt) and test (X_test) datasets using features.txt
    -the subject_train.txt and subject_test.txt files were merged to their respective X dataset
    -the Y_train.txt and Y_test.txt files were merged to their respective X dataset
    -column names were added for subject and Activity variables   
    -the training and test datasets were merged into one file called AllData

3. The measurements for mean and standard deviation for each measurement were extracted
    -Columns that were mean or std_Dev variables were selected from features.txt to create a list, including the Subject and Activity columns
    -the list was used to subset the selected columns from AllData to create the Subset_mean_std file
    
3. Activity names were changed to the descriptive names in activity_labels.txt
    -The activity_label numeric values were replaced with actual names
    -the data was arranged by subject to order the data from Subject 1 to 30
    
4. The data set column names were replaced with descriptive variable names. 
    - The column names abbreviations were renamed to be more descriptive

5. The data from step 4 was used to create a second, independent tidy data set with the average of each variable for each activity and each subject.

##Description of the variables in the tidydata.txt file
 The final tidy dataset comprised 180 observations (average of all variables for subject and activity) and 68 variables
 $ Subject                                           : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Activity                                          : Factor w/ 6 levels "LAYING","SITTING",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ timeBodyAccelerometer-Mean-X                      : num  0.222 0.281 0.276 0.264 0.278 ...
 $ timeBodyAccelerometer-Mean-Y                      : num  -0.0405 -0.0182 -0.019 -0.015 -0.0183 ...
 $ timeBodyAccelerometer-Mean-Z                      : num  -0.113 -0.107 -0.101 -0.111 -0.108 ...
 $ timeBodyAccelerometer-StdDev-X                    : num  -0.928 -0.974 -0.983 -0.954 -0.966 ...
 $ timeBodyAccelerometer-StdDev-Y                    : num  -0.837 -0.98 -0.962 -0.942 -0.969 ...
 $ timeBodyAccelerometer-StdDev-Z                    : num  -0.826 -0.984 -0.964 -0.963 -0.969 ...
 $ timeGravityAccelerometer-Mean-X                   : num  -0.249 -0.51 -0.242 -0.421 -0.483 ...
 $ timeGravityAccelerometer-Mean-Y                   : num  0.706 0.753 0.837 0.915 0.955 ...
 $ timeGravityAccelerometer-Mean-Z                   : num  0.446 0.647 0.489 0.342 0.264 ...
 $ timeGravityAccelerometer-StdDev-X                 : num  -0.897 -0.959 -0.983 -0.921 -0.946 ...
 $ timeGravityAccelerometer-StdDev-Y                 : num  -0.908 -0.988 -0.981 -0.97 -0.986 ...
 $ timeGravityAccelerometer-StdDev-Z                 : num  -0.852 -0.984 -0.965 -0.976 -0.977 ...
 $ timeBodyAccelerometerJerk-Mean-X                  : num  0.0811 0.0826 0.077 0.0934 0.0848 ...
 $ timeBodyAccelerometerJerk-Mean-Y                  : num  0.00384 0.01225 0.0138 0.00693 0.00747 ...
 $ timeBodyAccelerometerJerk-Mean-Z                  : num  0.01083 -0.0018 -0.00436 -0.00641 -0.00304 ...
 $ timeBodyAccelerometerJerk-StdDev-X                : num  -0.958 -0.986 -0.981 -0.978 -0.983 ...
 $ timeBodyAccelerometerJerk-StdDev-Y                : num  -0.924 -0.983 -0.969 -0.942 -0.965 ...
 $ timeBodyAccelerometerJerk-StdDev-Z                : num  -0.955 -0.988 -0.982 -0.979 -0.985 ...
 $ timeBodyGyroscope-Mean-X                          : num  -0.01655 -0.01848 -0.02082 -0.00923 -0.02189 ...
 $ timeBodyGyroscope-Mean-Y                          : num  -0.0645 -0.1118 -0.0719 -0.093 -0.0799 ...
 $ timeBodyGyroscope-Mean-Z                          : num  0.149 0.145 0.138 0.17 0.16 ...
 $ timeBodyGyroscope-StdDev-X                        : num  -0.874 -0.988 -0.975 -0.973 -0.979 ...
 $ timeBodyGyroscope-StdDev-Y                        : num  -0.951 -0.982 -0.977 -0.961 -0.977 ...
 $ timeBodyGyroscope-StdDev-Z                        : num  -0.908 -0.96 -0.964 -0.962 -0.961 ...
 $ timeBodyGyroscopeJerk-Mean-X                      : num  -0.107 -0.102 -0.1 -0.105 -0.102 ...
 $ timeBodyGyroscopeJerk-Mean-Y                      : num  -0.0415 -0.0359 -0.039 -0.0381 -0.0404 ...
 $ timeBodyGyroscopeJerk-Mean-Z                      : num  -0.0741 -0.0702 -0.0687 -0.0712 -0.0708 ...
 $ timeBodyGyroscopeJerk-StdDev-X                    : num  -0.919 -0.993 -0.98 -0.975 -0.983 ...
 $ timeBodyGyroscopeJerk-StdDev-Y                    : num  -0.968 -0.99 -0.987 -0.987 -0.984 ...
 $ timeBodyGyroscopeJerk-StdDev-Z                    : num  -0.958 -0.988 -0.983 -0.984 -0.99 ...
 $ timeBodyAccelerometerMagnitude-Mean               : num  -0.842 -0.977 -0.973 -0.955 -0.967 ...
 $ timeBodyAccelerometerMagnitude-StdDev             : num  -0.795 -0.973 -0.964 -0.931 -0.959 ...
 $ timeGravityAccelerometerMagnitude-Mean            : num  -0.842 -0.977 -0.973 -0.955 -0.967 ...
 $ timeGravityAccelerometerMagnitude-StdDev          : num  -0.795 -0.973 -0.964 -0.931 -0.959 ...
 $ timeBodyAccelerometerJerkMagnitude-Mean           : num  -0.954 -0.988 -0.979 -0.97 -0.98 ...
 $ timeBodyAccelerometerJerkMagnitude-StdDev         : num  -0.928 -0.986 -0.976 -0.961 -0.977 ...
 $ timeBodyGyroscopeMagnitude-Mean                   : num  -0.875 -0.95 -0.952 -0.93 -0.947 ...
 $ timeBodyGyroscopeMagnitude-StdDev                 : num  -0.819 -0.961 -0.954 -0.947 -0.958 ...
 $ timeBodyGyroscopeJerkMagnitude-Mean               : num  -0.963 -0.992 -0.987 -0.985 -0.986 ...
 $ timeBodyGyroscopeJerkMagnitude-StdDev             : num  -0.936 -0.99 -0.983 -0.983 -0.984 ...
 $ frequencyBodyAccelerometer-Mean-X                 : num  -0.939 -0.977 -0.981 -0.959 -0.969 ...
 $ frequencyBodyAccelerometer-Mean-Y                 : num  -0.867 -0.98 -0.961 -0.939 -0.965 ...
 $ frequencyBodyAccelerometer-Mean-Z                 : num  -0.883 -0.984 -0.968 -0.968 -0.977 ...
 $ frequencyBodyAccelerometer-StdDev-X               : num  -0.924 -0.973 -0.984 -0.952 -0.965 ...
 $ frequencyBodyAccelerometer-StdDev-Y               : num  -0.834 -0.981 -0.964 -0.946 -0.973 ...
 $ frequencyBodyAccelerometer-StdDev-Z               : num  -0.813 -0.985 -0.963 -0.962 -0.966 ...
 $ frequencyBodyAccelerometerJerk-Mean-X             : num  -0.957 -0.986 -0.981 -0.979 -0.983 ...
 $ frequencyBodyAccelerometerJerk-Mean-Y             : num  -0.922 -0.983 -0.969 -0.944 -0.965 ...
 $ frequencyBodyAccelerometerJerk-Mean-Z             : num  -0.948 -0.986 -0.979 -0.975 -0.983 ...
 $ frequencyBodyAccelerometerJerk-StdDev-X           : num  -0.964 -0.987 -0.983 -0.98 -0.986 ...
 $ frequencyBodyAccelerometerJerk-StdDev-Y           : num  -0.932 -0.985 -0.971 -0.944 -0.966 ...
 $ frequencyBodyAccelerometerJerk-StdDev-Z           : num  -0.961 -0.989 -0.984 -0.98 -0.986 ...
 $ frequencyBodyGyroscope-Mean-X                     : num  -0.85 -0.986 -0.97 -0.967 -0.976 ...
 $ frequencyBodyGyroscope-Mean-Y                     : num  -0.952 -0.983 -0.978 -0.972 -0.978 ...
 $ frequencyBodyGyroscope-Mean-Z                     : num  -0.909 -0.963 -0.962 -0.961 -0.963 ...
 $ frequencyBodyGyroscope-StdDev-X                   : num  -0.882 -0.989 -0.976 -0.975 -0.981 ...
 $ frequencyBodyGyroscope-StdDev-Y                   : num  -0.951 -0.982 -0.977 -0.956 -0.977 ...
 $ frequencyBodyGyroscope-StdDev-Z                   : num  -0.917 -0.963 -0.967 -0.966 -0.963 ...
 $ frequencyBodyAccelerometerMagnitude-Mean          : num  -0.862 -0.975 -0.966 -0.939 -0.962 ...
 $ frequencyBodyAccelerometerMagnitude-StdDev        : num  -0.798 -0.975 -0.968 -0.937 -0.963 ...
 $ frequencyBodyBodyAccelerometerJerkMagnitude-Mean  : num  -0.933 -0.985 -0.976 -0.962 -0.977 ...
 $ frequencyBodyBodyAccelerometerJerkMagnitude-StdDev: num  -0.922 -0.985 -0.975 -0.958 -0.976 ...
 $ frequencyBodyBodyGyroscopeMagnitude-Mean          : num  -0.862 -0.972 -0.965 -0.962 -0.968 ...
 $ frequencyBodyBodyGyroscopeMagnitude-StdDev        : num  -0.824 -0.961 -0.955 -0.947 -0.959 ...
 $ frequencyBodyBodyGyroscopeJerkMagnitude-Mean      : num  -0.942 -0.99 -0.984 -0.984 -0.985 ...
 $ frequencyBodyBodyGyroscopeJerkMagnitude-StdDev    : num  -0.933 -0.989 -0.983 -0.983 -0.983 ...

###Variables
Subject - An identifier of the subject who carried out the experiment (1-30)
Activity - Activity performed (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING)
For each record in the dataset, data is provided for:
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope.
- A 561-feature vector with time and frequency domain variables.

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain 
signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass 
Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation
mad(): Median absolute deviation 
max(): Largest value in array
min(): Smallest value in array
sma(): Signal magnitude area
energy(): Energy measure. Sum of the squares divided by the number of values. 
iqr(): Interquartile range 
entropy(): Signal entropy
arCoeff(): Autorregresion coefficients with Burg order equal to 4
correlation(): correlation coefficient between two signals
maxInds(): index of the frequency component with largest magnitude
meanFreq(): Weighted average of the frequency components to obtain a mean frequency
skewness(): skewness of the frequency domain signal 
kurtosis(): kurtosis of the frequency domain signal 
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
angle(): Angle between to vectors.

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean
tBodyAccMean
tBodyAccJerkMean
tBodyGyroMean
tBodyGyroJerkMean

The complete list of variables of each feature vector is available in 'features.txt'

##Sources
[http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones]()

